version: '2'
services:
# First Log Generator
 datagenerator1:
  container_name: data-generator1
  image: 'registry.gitlab.com/wizni/data-generator:master'
  environment:
  - LOG_FILE:/var/log/analytics/log1.log
  - FREQUENCY:5000
  volumes:
  - ./logs:/var/log/analytics/

# Second Log Generator
 datagenerator2:
  container_name: data-generator2
  image: 'registry.gitlab.com/wizni/data-generator:master'
  environment:
  - LOG_FILE:/var/log/analytics/log2.log
  - FREQUENCY:1000
  volumes:
  - ./logs:/var/log/analytics/

# Fluentd
 tdagent:
  container_name: td-agent
  image: 'wizni/td-agent:v0.1'
  volumes:
  - ./logs:/var/log/analytics/
  - ./td-agent/td-agent.conf:/etc/td-agent/td-agent.conf
  depends_on:
  - elasticsearch

# ElasticSearch
 elasticsearch:
  container_name: elasticsearch
  hostname: elasticsearch
  image: 'wizni/elasticsearch:v0.1'
  volumes:
  - ./esdata:/usr/share/elasticsearch/data

# Zeppelin
 zeppelin:
  container_name: zeppelin
  image: 'registry.gitlab.com/wizni/zeppelin:0.6.0-wiz-1.0.0'
  environment:
  - ELASTICSEARCH_URL=http://elasticsearch:9200
  ports:
  - "8080:8080"
  - "8081:8081"
  depends_on:
  - elasticsearch
